### ISSUE TITLE
Calling /test/ results in empty window and WARN message

### ISSUE THREAD

**Issue by Quix0r** [Pscheidl/InterceptorBug#1]
I have tested your app on Payara 173 (latest stable build) and all I get calling https://localhost:8181/payara-interceptor-bug-1.0/test/ in browser is an empty result plus a warning in logfile:

````
[2017-08-27T22:42:06.397+0200] [Payara 4.1] [WARN] [] [org.jboss.weld.Interceptor] [tid: _ThreadID=33 _ThreadName=http-thread-pool::http-listener-2(1)] [timeMillis: 1503866526397] [levelValue: 900] [[
  WELD-001703: Unable to determine the @Intercepted Bean<?> for [UnbackedAnnotatedField] @Intercepted @Inject private org.jboss.weld.probe.InvocationMonitor.interceptedBean]]
````

This happens on each time. CDI Development Mode is explicitly enabled. Is this wanted and I see a fixed bug? Or still buggy?

**Comment by Quix0r** [comment]
I have activated the interceptor as shown in your example and now the warning is gone but still no result in browser. I would recommend to output something like **Test passed!** so the tester has a response for success.

**Comment by Pscheidl** [comment]
Hello, I have retested the reported behavior on a freshly downloaded Payara Server 173 - Full.

The configuration of the server and the application is default. An empty beans.xml with bean discovery mode set to "all". No manual interceptor enabling. **The interceptor is properly enabled and the test application works.**
------------------------
2nd question
------------------------
You are getting a blank screen because the status code in HTTP response is set to 200 OK, while the body is empty. As you suggest, for people who might want to try it, I've added an informative line of text.

Also, if you enable warning log level, you can see output in the console:

```
09:40:34,025 WARN  [com.github.pscheidl.fortee.FailsafeInterceptor] (default task-4) Failsafe interceptor caught an exception: : java.lang.RuntimeException: Failed on purpose
	at cz.pscheidl.test.SomeBean.greet(SomeBean.java:20)
	at cz.pscheidl.test.SomeBean$Proxy$_$$_WeldSubclass.greet$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at com.github.pscheidl.fortee.FailsafeInterceptor.guard(FailsafeInterceptor.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at cz.pscheidl.test.SomeBean$Proxy$_$$_WeldSubclass.greet(Unknown Source)
	at cz.pscheidl.test.SomeBean$Proxy$_$$_WeldClientProxy.greet(Unknown Source)
	at cz.pscheidl.test.Endpoint.test(Endpoint.java:25)
	at cz.pscheidl.test.Endpoint$Proxy$_$$_WeldClientProxy.test(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Quix0r** [comment]
I'm sorry, but I get this with a fresh built:

````
Caused by: java.lang.ClassNotFoundException: cz.pscheidl.fortee.FailsafeInterceptor
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1655)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1501)
        at org.glassfish.weld.ResourceLoaderImpl.classForName(ResourceLoaderImpl.java:75)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:277)
        ... 71 more
````

I can see that the required JARs are bundled in. I had similar issues with my Payara where a Producer (with proper `@Produces` annotation on the producing method) was not discoverable. I must mention that I use JSF 2.3.2 as I now have converters with generics (which is really cool). Maybe an issue in JSF 2.3.2? I undeploy now my 2.3 app, switch the javax.faces.jar files and retest again.

**Comment by Pscheidl** [comment]
Can I see your application ? Class not found is weird. Looks like packaging problem to me at first sight. 

Can we contact each other somewhere else so we can discuss this faster ? I bet you are not able to share your app repository. Skype ? Hangouts ? 

I can't do much with pure stacktrace. 

⁣Odesláno z BlueMail ​

3. 9. 2017 14:36, 14:36, "Roland Häder" <notifications@github.com> napsal/a:

**Comment by Quix0r** [comment]
It happens with your application here:
https://cloud.mxchange.org/index.php/s/149vSQYmDeENiuY/download?path=%2FPayara&files=payara-interceptor-bug-1.0.war

**Comment by Pscheidl** [comment]
Downloaded. Will give it a try.

**Comment by Pscheidl** [comment]
I took a look at your application. There are numerous problems with it. If you do a clean copy of this repository, you will see an empty beans.xml. With clean beans.xml (no interceptor enabled explicitely), it works on Payara 173.

What you did was to include

```
    <interceptors>
        <class>cz.pscheidl.fortee.FailsafeInterceptor</class>
    </interceptors>

```

because this was the information written in README of this repository. I recently updated the version used and forgot to update the README.

**You are using a newer version** of FortEE and the package for the interceptor changed (FortEE was still alpha back then).The **correct** manual way to enable the interceptor is demonstrated below (the package structure changed).

```
    <interceptors>
        <class>com.github.pscheidl.fortee.FailsafeInterceptor</class>
    </interceptors>
```

Once again, this is no longer required, since FortEE activates its interceptor automatically and no interaction with beans.xml is required. The solution is to enter the correct package or to remove the <interceptors> block completely.

**Comment by Quix0r** [comment]
Thank you for explaining it in such a detail. I understand the situation now. I have removed the interceptor registration from `beans.xml` and it deploys + invoking `/test/` says **Test passed**. Maybe the @payara team can include this test in their test suit?

For me, this case is closes. 👍

**Comment by Pscheidl** [comment]
Glad to help.
